version: '3'
services:
  broker:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./broker/config:/mosquitto/config:ro
      - ./broker/data:/mosquitto/data:rw
      - ./broker/log:/mosquitto/log:rw
  
  sub:
    build: sub
    image: donkey-subscriber:1.0
    container_name: node
    tty: true
    volumes:
      - ./sub/app:/app
    ports:
      - 3000:3000
    depends_on:
      - broker
      - pub
  
  pub:
    build: pub
    image: donkey-publisher:1.0
    container_name: python
    tty: true
    volumes:
      - ./pub/app:/app
    depends_on:
      - broker

